### ISSUE TITLE
Add ground station battery status to osd

### ISSUE THREAD

**Issue by RoboSchmied** [gehee/FPVue_android#6]
For box google usage it would be helpful to have the battery status of the ground station (android device where FPVue runs) to the screen the whole time.

## later improvements
- This can also include a warning before reaching the 20% mark when the decoding gets bad. 
- Offered as an option in the config tab to switch visibility for users that do not need this.

**Comment by gehee** [comment]
Added in https://github.com/gehee/FPVue_android/commit/59a63dc5428335e5d0b6928364465f429ed93a2d.
Please wait for the next release.
